version: '3'

services:

  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - ${HOME}/.mongodb:/data/db
    networks:
      default:
        aliases:
          - mongodb.host

  ssshare:
    build: .
    restart: always
    volumes:
      - ./ssshare:/usr/src/app/ssshare
    depends_on:
      - mongodb
    extra_hosts:
      - "youneed.win:104.31.74.55"
      - "www.youneed.win:104.31.74.55"
